addpath function

% Cargo una imagen de prueba
data = imread('resources\rubik.png');

imshow(data);

btnChangeUI = uicontrol('Style', 'pushbutton', 'String', 'Cambiar Color',...
    'Position', [10 10 120 30],...
    'Callback', @changeColor);
btnEndUI = uicontrol('Style', 'pushbutton', 'String', 'Finalizar',...
    'Position', [140 10 120 30],...
    'Callback', @stopVid);
varianceUI = uicontrol('Style', 'slider',...
    'Min', 0, 'Max', 120, 'Value', 10,...
    'Position', [280 10 80 30],...
    'Callback', @changeVariance);
scoreUI = uicontrol('Style', 'text',...
   'String', strcat('Explotados: 0'),...
   'Units','pixels',...
   'HorizontalAlignment','left',...
   'ForegroundColor', [0, 0, 1],...
   'FontSize', 24,...
   'Position', [380 10 220 40]);


rmpath function;